import { CompletionItemKind } from 'vscode-languageserver/node';

export const KEYWORDS: Record<string, { label: string; detail: string; documentation: string; kind: CompletionItemKind }> = {
    'dim': { label: 'Dim', detail: 'Dim keyword', documentation: 'Declares and allocates storage space for one or more variables.', kind: CompletionItemKind.Keyword },
    'if': { label: 'If', detail: 'If keyword', documentation: 'Conditionally executes a group of statements, depending on the value of an expression.', kind: CompletionItemKind.Keyword },
    'then': { label: 'Then', detail: 'Then keyword', documentation: 'Introduces a statement block to be compiled or executed.', kind: CompletionItemKind.Keyword },
    'else': { label: 'Else', detail: 'Else keyword', documentation: 'Introduces a statement block to be compiled or executed if the condition is False.', kind: CompletionItemKind.Keyword },
    'end if': { label: 'End If', detail: 'End If keyword', documentation: 'Ends an If...Then...Else block.', kind: CompletionItemKind.Keyword },
    'sub': { label: 'Sub', detail: 'Sub keyword', documentation: 'Declares the name, parameters, and code that define a Sub procedure.', kind: CompletionItemKind.Keyword },
    'function': { label: 'Function', detail: 'Function keyword', documentation: 'Declares the name, parameters, and code that define a Function procedure.', kind: CompletionItemKind.Keyword },
    'end sub': { label: 'End Sub', detail: 'End Sub keyword', documentation: 'Terminates the definition of this procedure.', kind: CompletionItemKind.Keyword },
    'end function': { label: 'End Function', detail: 'End Function keyword', documentation: 'Terminates the definition of this procedure.', kind: CompletionItemKind.Keyword },
    'for': { label: 'For', detail: 'For keyword', documentation: 'Repeats a group of statements a specified number of times.', kind: CompletionItemKind.Keyword },
    'next': { label: 'Next', detail: 'Next keyword', documentation: 'Ends a For...Next loop.', kind: CompletionItemKind.Keyword },
    'while': { label: 'While', detail: 'While keyword', documentation: 'Executes a series of statements as long as a given condition is True.', kind: CompletionItemKind.Keyword },
    'wend': { label: 'Wend', detail: 'Wend keyword', documentation: 'Ends a While...Wend loop.', kind: CompletionItemKind.Keyword },
    'do': { label: 'Do', detail: 'Do keyword', documentation: 'Repeats a block of statements while a Boolean condition is True or until the condition becomes True.', kind: CompletionItemKind.Keyword },
    'loop': { label: 'Loop', detail: 'Loop keyword', documentation: 'Ends a Do...Loop.', kind: CompletionItemKind.Keyword },
    'as': { label: 'As', detail: 'As keyword', documentation: 'Used in a Dim, ReDim, Static, Private, Public, or Const statement to declare the data type of a variable.', kind: CompletionItemKind.Keyword },
    'integer': { label: 'Integer', detail: 'Integer data type', documentation: 'Holds signed 32-bit (4-byte) integers ranging in value from -2,147,483,648 through 2,147,483,647.', kind: CompletionItemKind.Class },
    'string': { label: 'String', detail: 'String data type', documentation: 'Holds sequences of unsigned 16-bit (2-byte) code points ranging in value from 0 through 65535.', kind: CompletionItemKind.Class },
    'boolean': { label: 'Boolean', detail: 'Boolean data type', documentation: 'Holds values that can be only True or False.', kind: CompletionItemKind.Class },
    'double': { label: 'Double', detail: 'Double data type', documentation: 'Holds signed IEEE 64-bit (8-byte) double-precision floating-point numbers.', kind: CompletionItemKind.Class },
    'date': { label: 'Date', detail: 'Date data type', documentation: 'Holds IEEE 64-bit (8-byte) values that represent dates ranging from January 1 of the year 0001 through December 31 of the year 9999.', kind: CompletionItemKind.Class },
    'long': { label: 'Long', detail: 'Long data type', documentation: 'Holds signed 64-bit (8-byte) integers ranging in value from -9,223,372,036,854,775,808 through 9,223,372,036,854,775,807.', kind: CompletionItemKind.Class },
    'byte': { label: 'Byte', detail: 'Byte data type', documentation: 'Holds unsigned 8-bit (1-byte) integers ranging in value from 0 through 255.', kind: CompletionItemKind.Class },
    'object': { label: 'Object', detail: 'Object data type', documentation: 'Points to any object.', kind: CompletionItemKind.Class },
    'public': { label: 'Public', detail: 'Public keyword', documentation: 'Specifies that one or more declared programming elements have no access restrictions.', kind: CompletionItemKind.Keyword },
    'private': { label: 'Private', detail: 'Private keyword', documentation: 'Specifies that one or more declared programming elements are accessible only from within their declaration context.', kind: CompletionItemKind.Keyword },
    'const': { label: 'Const', detail: 'Const keyword', documentation: 'Declares and defines one or more constants.', kind: CompletionItemKind.Keyword },
    'true': { label: 'True', detail: 'True literal', documentation: 'Represents a Boolean value.', kind: CompletionItemKind.Keyword },
    'false': { label: 'False', detail: 'False literal', documentation: 'Represents a Boolean value.', kind: CompletionItemKind.Keyword },
    'new': { label: 'New', detail: 'New keyword', documentation: 'Creates a new object instance.', kind: CompletionItemKind.Keyword }
};
